/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cse.pkg434.ai;


import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;


public class Hearts extends javax.swing.JFrame {

    /**
     * Creates new form MainGui
     */
    public Hearts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player1 = new javax.swing.JPanel();
        player1card1 = new javax.swing.JLabel();
        player1card2 = new javax.swing.JLabel();
        player1card3 = new javax.swing.JLabel();
        player1card4 = new javax.swing.JLabel();
        player1card5 = new javax.swing.JLabel();
        player1card6 = new javax.swing.JLabel();
        player1card7 = new javax.swing.JLabel();
        player1card8 = new javax.swing.JLabel();
        player1card9 = new javax.swing.JLabel();
        player1card10 = new javax.swing.JLabel();
        player1card11 = new javax.swing.JLabel();
        player1card12 = new javax.swing.JLabel();
        player1card13 = new javax.swing.JLabel();
        labelPlayer1 = new javax.swing.JLabel();
        player2 = new javax.swing.JPanel();
        player2card1 = new javax.swing.JLabel();
        player2card2 = new javax.swing.JLabel();
        player2card3 = new javax.swing.JLabel();
        player2card4 = new javax.swing.JLabel();
        player2card5 = new javax.swing.JLabel();
        player2card6 = new javax.swing.JLabel();
        player2card7 = new javax.swing.JLabel();
        player2card8 = new javax.swing.JLabel();
        player2card9 = new javax.swing.JLabel();
        player2card10 = new javax.swing.JLabel();
        player2card11 = new javax.swing.JLabel();
        player2card12 = new javax.swing.JLabel();
        player2card13 = new javax.swing.JLabel();
        labelPlayer2 = new javax.swing.JLabel();
        player4 = new javax.swing.JPanel();
        player4card1 = new javax.swing.JLabel();
        player4card2 = new javax.swing.JLabel();
        player4card3 = new javax.swing.JLabel();
        player4card4 = new javax.swing.JLabel();
        player4card5 = new javax.swing.JLabel();
        player4card6 = new javax.swing.JLabel();
        player4card7 = new javax.swing.JLabel();
        player4card8 = new javax.swing.JLabel();
        player4card9 = new javax.swing.JLabel();
        player4card10 = new javax.swing.JLabel();
        player4card11 = new javax.swing.JLabel();
        player4card12 = new javax.swing.JLabel();
        player4card13 = new javax.swing.JLabel();
        labelPlayer4 = new javax.swing.JLabel();
        player3 = new javax.swing.JPanel();
        player3card1 = new javax.swing.JLabel();
        player3card2 = new javax.swing.JLabel();
        player3card3 = new javax.swing.JLabel();
        player3card4 = new javax.swing.JLabel();
        player3card5 = new javax.swing.JLabel();
        player3card6 = new javax.swing.JLabel();
        player3card7 = new javax.swing.JLabel();
        player3card8 = new javax.swing.JLabel();
        player3card9 = new javax.swing.JLabel();
        player3card10 = new javax.swing.JLabel();
        player3card11 = new javax.swing.JLabel();
        player3card12 = new javax.swing.JLabel();
        player3card13 = new javax.swing.JLabel();
        labelPlayer3 = new javax.swing.JLabel();
        player5 = new javax.swing.JPanel();
        boardcard1 = new javax.swing.JLabel();
        boardcard2 = new javax.swing.JLabel();
        boardcard3 = new javax.swing.JLabel();
        boardcard4 = new javax.swing.JLabel();
        labelBoard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        player1card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player1card1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player1card1MouseClicked(evt);
            }
        });

        player1card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player1card2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player1card2MouseClicked(evt);
            }
        });

        player1card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player1card3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player1card3MouseClicked(evt);
            }
        });

        player1card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player1card4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player1card4MouseClicked(evt);
            }
        });

        player1card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player1card5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player1card5MouseClicked(evt);
            }
        });

        player1card6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player1card6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player1card6MouseClicked(evt);
            }
        });

        player1card7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player1card7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player1card7MouseClicked(evt);
            }
        });

        player1card8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player1card8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player1card8MouseClicked(evt);
            }
        });

        player1card9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player1card9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player1card9MouseClicked(evt);
            }
        });

        player1card10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player1card10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player1card10MouseClicked(evt);
            }
        });

        player1card11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player1card11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player1card11MouseClicked(evt);
            }
        });

        player1card12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player1card12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player1card12MouseClicked(evt);
            }
        });

        player1card13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player1card13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player1card13MouseClicked(evt);
            }
        });

        labelPlayer1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPlayer1.setText("Player 1");

        javax.swing.GroupLayout player1Layout = new javax.swing.GroupLayout(player1);
        player1.setLayout(player1Layout);
        player1Layout.setHorizontalGroup(
            player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(player1Layout.createSequentialGroup()
                        .addComponent(player1card11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player1card12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player1card13))
                    .addGroup(player1Layout.createSequentialGroup()
                        .addGroup(player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(player1Layout.createSequentialGroup()
                                .addComponent(player1card1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(player1card2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(player1card3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(player1card4))
                            .addGroup(player1Layout.createSequentialGroup()
                                .addComponent(player1card6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(player1card7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(player1card8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(player1card9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(player1card10)
                            .addComponent(player1card5)))
                    .addComponent(labelPlayer1))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        player1Layout.setVerticalGroup(
            player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, player1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelPlayer1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(player1Layout.createSequentialGroup()
                        .addGroup(player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(player1card1)
                                .addComponent(player1card3)
                                .addComponent(player1card2))
                            .addComponent(player1card4))
                        .addGroup(player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, player1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(player1card7)
                                        .addComponent(player1card8)
                                        .addComponent(player1card9))
                                    .addGroup(player1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(player1card10)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(player1card12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(player1card13, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, player1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(player1card6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(player1card11))))
                    .addComponent(player1card5))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        player2card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player2card1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player2card1MouseClicked(evt);
            }
        });

        player2card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player2card2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player2card2MouseClicked(evt);
            }
        });

        player2card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player2card3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player2card3MouseClicked(evt);
            }
        });

        player2card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player2card4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player2card4MouseClicked(evt);
            }
        });

        player2card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player2card5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player2card5MouseClicked(evt);
            }
        });

        player2card6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player2card6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player2card6MouseClicked(evt);
            }
        });

        player2card7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player2card7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player2card7MouseClicked(evt);
            }
        });

        player2card8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player2card8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player2card8MouseClicked(evt);
            }
        });

        player2card9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player2card9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player2card9MouseClicked(evt);
            }
        });

        player2card10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player2card10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player2card10MouseClicked(evt);
            }
        });

        player2card11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player2card11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player2card11MouseClicked(evt);
            }
        });

        player2card12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player2card12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player2card12MouseClicked(evt);
            }
        });

        player2card13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player2card13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player2card13MouseClicked(evt);
            }
        });

        labelPlayer2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPlayer2.setText("Player 2");

        javax.swing.GroupLayout player2Layout = new javax.swing.GroupLayout(player2);
        player2.setLayout(player2Layout);
        player2Layout.setHorizontalGroup(
            player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(player2Layout.createSequentialGroup()
                        .addComponent(player2card1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player2card2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player2card3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player2card4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player2card5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player2card6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player2card7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(player2card8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player2card9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player2card10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player2card11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(player2card12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(player2card13))
                    .addComponent(labelPlayer2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        player2Layout.setVerticalGroup(
            player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, player2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPlayer2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(player2card2)
                        .addGroup(player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(player2card3)
                                .addComponent(player2card1)
                                .addComponent(player2card4))
                            .addComponent(player2card5)
                            .addComponent(player2card7)
                            .addComponent(player2card8)
                            .addComponent(player2card6))
                        .addComponent(player2card9)
                        .addGroup(player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(player2card11)
                            .addComponent(player2card10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(player2card12)))
                    .addComponent(player2card13))
                .addGap(371, 371, 371))
        );

        player4card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/C2.jpg"))); // NOI18N
        player4card1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player4card1MouseClicked(evt);
            }
        });

        player4card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/C3.jpg"))); // NOI18N
        player4card2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player4card2MouseClicked(evt);
            }
        });

        player4card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/C4.jpg"))); // NOI18N
        player4card3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player4card3MouseClicked(evt);
            }
        });

        player4card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/C5.jpg"))); // NOI18N
        player4card4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player4card4MouseClicked(evt);
            }
        });

        player4card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/C6.jpg"))); // NOI18N
        player4card5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player4card5MouseClicked(evt);
            }
        });

        player4card6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/C7.jpg"))); // NOI18N
        player4card6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player4card6MouseClicked(evt);
            }
        });

        player4card7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/C8.jpg"))); // NOI18N
        player4card7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player4card7MouseClicked(evt);
            }
        });

        player4card8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/C9.jpg"))); // NOI18N
        player4card8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player4card8MouseClicked(evt);
            }
        });

        player4card9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/C10.jpg"))); // NOI18N
        player4card9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player4card9MouseClicked(evt);
            }
        });

        player4card10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CJ.jpg"))); // NOI18N
        player4card10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player4card10MouseClicked(evt);
            }
        });

        player4card11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CQ.jpg"))); // NOI18N
        player4card11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player4card11MouseClicked(evt);
            }
        });

        player4card12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CK.jpg"))); // NOI18N
        player4card12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player4card12MouseClicked(evt);
            }
        });

        player4card13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CA.jpg"))); // NOI18N
        player4card13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player4card13MouseClicked(evt);
            }
        });

        labelPlayer4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPlayer4.setText("Player 4 (Me)");

        javax.swing.GroupLayout player4Layout = new javax.swing.GroupLayout(player4);
        player4.setLayout(player4Layout);
        player4Layout.setHorizontalGroup(
            player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(player4Layout.createSequentialGroup()
                        .addComponent(player4card1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player4card2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(player4card3)
                        .addGap(2, 2, 2)
                        .addComponent(player4card4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player4card5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player4card6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player4card7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player4card8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(player4card9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player4card10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player4card11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player4card12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(player4card13))
                    .addComponent(labelPlayer4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        player4Layout.setVerticalGroup(
            player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, player4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPlayer4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(player4card2)
                    .addGroup(player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(player4card1)
                            .addComponent(player4card4)
                            .addComponent(player4card3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(player4card5)
                        .addComponent(player4card7)
                        .addComponent(player4card6))
                    .addGroup(player4Layout.createSequentialGroup()
                        .addGroup(player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(player4card13)
                            .addGroup(player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(player4card11)
                                    .addGroup(player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(player4card9)
                                            .addComponent(player4card8))
                                        .addGroup(player4Layout.createSequentialGroup()
                                            .addComponent(player4card10)
                                            .addGap(1, 1, 1))))
                                .addGroup(player4Layout.createSequentialGroup()
                                    .addComponent(player4card12)
                                    .addGap(2, 2, 2))))
                        .addGap(1, 1, 1)))
                .addContainerGap())
        );

        player3card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player3card1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player3card1MouseClicked(evt);
            }
        });

        player3card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player3card2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player3card2MouseClicked(evt);
            }
        });

        player3card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player3card3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player3card3MouseClicked(evt);
            }
        });

        player3card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player3card4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player3card4MouseClicked(evt);
            }
        });

        player3card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player3card5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player3card5MouseClicked(evt);
            }
        });

        player3card6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player3card6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player3card6MouseClicked(evt);
            }
        });

        player3card7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player3card7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player3card7MouseClicked(evt);
            }
        });

        player3card8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player3card8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player3card8MouseClicked(evt);
            }
        });

        player3card9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player3card9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player3card9MouseClicked(evt);
            }
        });

        player3card10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player3card10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player3card10MouseClicked(evt);
            }
        });

        player3card11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player3card11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player3card11MouseClicked(evt);
            }
        });

        player3card12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player3card12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player3card12MouseClicked(evt);
            }
        });

        player3card13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me.jpg"))); // NOI18N
        player3card13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player3card13MouseClicked(evt);
            }
        });

        labelPlayer3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPlayer3.setText("Player 3");

        javax.swing.GroupLayout player3Layout = new javax.swing.GroupLayout(player3);
        player3.setLayout(player3Layout);
        player3Layout.setHorizontalGroup(
            player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(player3Layout.createSequentialGroup()
                        .addComponent(player3card11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player3card12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player3card13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(player3Layout.createSequentialGroup()
                        .addGroup(player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(player3Layout.createSequentialGroup()
                                .addComponent(player3card6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(player3card7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(player3card8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(player3card9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(player3card10))
                            .addGroup(player3Layout.createSequentialGroup()
                                .addComponent(player3card1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(player3card2)
                                .addGap(8, 8, 8)
                                .addComponent(player3card3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(player3card4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(player3card5))
                            .addComponent(labelPlayer3))
                        .addGap(0, 20, Short.MAX_VALUE))))
        );
        player3Layout.setVerticalGroup(
            player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, player3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPlayer3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, player3Layout.createSequentialGroup()
                        .addGroup(player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(player3card1)
                                .addComponent(player3card2)
                                .addComponent(player3card3))
                            .addComponent(player3card4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(player3card5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(player3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(player3card6)
                                    .addComponent(player3card7)))
                            .addGroup(player3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(player3card10)
                                    .addComponent(player3card9)))))
                    .addComponent(player3card8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(7, 7, 7)
                .addGroup(player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(player3card12)
                    .addComponent(player3card11)
                    .addComponent(player3card13))
                .addContainerGap())
        );

        boardcard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/opponent.jpg"))); // NOI18N
        boardcard1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boardcard1MouseClicked(evt);
            }
        });

        boardcard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/opponent.jpg"))); // NOI18N
        boardcard2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boardcard2MouseClicked(evt);
            }
        });

        boardcard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/opponent.jpg"))); // NOI18N
        boardcard3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boardcard3MouseClicked(evt);
            }
        });

        boardcard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/opponent.jpg"))); // NOI18N
        boardcard4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boardcard4MouseClicked(evt);
            }
        });

        labelBoard.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelBoard.setText("Board");

        javax.swing.GroupLayout player5Layout = new javax.swing.GroupLayout(player5);
        player5.setLayout(player5Layout);
        player5Layout.setHorizontalGroup(
            player5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player5Layout.createSequentialGroup()
                .addGroup(player5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(player5Layout.createSequentialGroup()
                        .addGroup(player5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(boardcard1)
                            .addComponent(boardcard3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(player5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boardcard2)
                            .addComponent(boardcard4)))
                    .addGroup(player5Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(labelBoard)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        player5Layout.setVerticalGroup(
            player5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, player5Layout.createSequentialGroup()
                .addComponent(labelBoard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(player5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boardcard2)
                    .addComponent(boardcard1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(player5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boardcard3)
                    .addComponent(boardcard4))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(player4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(player1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(player5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(player3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(player2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(player1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(player5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void player2card1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player2card1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player2card1MouseClicked

    private void player2card3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player2card3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player2card3MouseClicked

    private void player2card4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player2card4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player2card4MouseClicked

    private void player2card5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player2card5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player2card5MouseClicked

    private void player2card7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player2card7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player2card7MouseClicked

    private void player2card8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player2card8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player2card8MouseClicked

    private void player2card9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player2card9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player2card9MouseClicked

    private void player2card10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player2card10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player2card10MouseClicked

    private void player2card12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player2card12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player2card12MouseClicked

    private void player2card11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player2card11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player2card11MouseClicked

    private void player2card2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player2card2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player2card2MouseClicked

    private void player2card6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player2card6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player2card6MouseClicked

    private void player2card13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player2card13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player2card13MouseClicked

    private void player4card1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player4card1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player4card1MouseClicked

    private void player4card2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player4card2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player4card2MouseClicked

    private void player4card3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player4card3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player4card3MouseClicked

    private void player4card4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player4card4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player4card4MouseClicked

    private void player4card5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player4card5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player4card5MouseClicked

    private void player4card6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player4card6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player4card6MouseClicked

    private void player4card7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player4card7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player4card7MouseClicked

    private void player4card8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player4card8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player4card8MouseClicked

    private void player4card9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player4card9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player4card9MouseClicked

    private void player4card10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player4card10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player4card10MouseClicked

    private void player4card11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player4card11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player4card11MouseClicked

    private void player4card12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player4card12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player4card12MouseClicked

    private void player4card13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player4card13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player4card13MouseClicked

    private void player3card13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player3card13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player3card13MouseClicked

    private void player3card12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player3card12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player3card12MouseClicked

    private void player3card11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player3card11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player3card11MouseClicked

    private void player3card10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player3card10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player3card10MouseClicked

    private void player3card9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player3card9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player3card9MouseClicked

    private void player3card8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player3card8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player3card8MouseClicked

    private void player3card7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player3card7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player3card7MouseClicked

    private void player3card6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player3card6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player3card6MouseClicked

    private void player3card5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player3card5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player3card5MouseClicked

    private void player3card4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player3card4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player3card4MouseClicked

    private void player3card3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player3card3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player3card3MouseClicked

    private void player3card2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player3card2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player3card2MouseClicked

    private void player3card1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player3card1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player3card1MouseClicked

    private void player1card13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player1card13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player1card13MouseClicked

    private void player1card12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player1card12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player1card12MouseClicked

    private void player1card11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player1card11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player1card11MouseClicked

    private void player1card10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player1card10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player1card10MouseClicked

    private void player1card9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player1card9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player1card9MouseClicked

    private void player1card8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player1card8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player1card8MouseClicked

    private void player1card7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player1card7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player1card7MouseClicked

    private void player1card6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player1card6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player1card6MouseClicked

    private void player1card5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player1card5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player1card5MouseClicked

    private void player1card4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player1card4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player1card4MouseClicked

    private void player1card3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player1card3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player1card3MouseClicked

    private void player1card2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player1card2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player1card2MouseClicked

    private void player1card1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player1card1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_player1card1MouseClicked

    private void boardcard1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boardcard1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_boardcard1MouseClicked

    private void boardcard2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boardcard2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_boardcard2MouseClicked

    private void boardcard3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boardcard3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_boardcard3MouseClicked

    private void boardcard4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boardcard4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_boardcard4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hearts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hearts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hearts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hearts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //JOptionPane.showMessageDialog(null, "Which Level ??? 1) Beginner ,  2)Intermediate, 3)Hard ??   (only give the number)");
                String rawinputOption = JOptionPane.showInputDialog(null, "1. Beginner ,  2.Intermediate, 3.Hard ??   (only give the number)", "Which Level ???", QUESTION_MESSAGE);
                int inputOption = Integer.parseInt(rawinputOption);
                if(inputOption == 1){
                    new Hearts().setVisible(true);
                }
                else if (inputOption == 2){
                    new Hearts().setVisible(true);
                }
                else if(inputOption == 3){
                    System.exit(0);
                }
                else {
                   System.exit(0);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boardcard1;
    private javax.swing.JLabel boardcard2;
    private javax.swing.JLabel boardcard3;
    private javax.swing.JLabel boardcard4;
    private javax.swing.JLabel labelBoard;
    private javax.swing.JLabel labelPlayer1;
    private javax.swing.JLabel labelPlayer2;
    private javax.swing.JLabel labelPlayer3;
    private javax.swing.JLabel labelPlayer4;
    private javax.swing.JPanel player1;
    private javax.swing.JLabel player1card1;
    private javax.swing.JLabel player1card10;
    private javax.swing.JLabel player1card11;
    private javax.swing.JLabel player1card12;
    private javax.swing.JLabel player1card13;
    private javax.swing.JLabel player1card2;
    private javax.swing.JLabel player1card3;
    private javax.swing.JLabel player1card4;
    private javax.swing.JLabel player1card5;
    private javax.swing.JLabel player1card6;
    private javax.swing.JLabel player1card7;
    private javax.swing.JLabel player1card8;
    private javax.swing.JLabel player1card9;
    private javax.swing.JPanel player2;
    private javax.swing.JLabel player2card1;
    private javax.swing.JLabel player2card10;
    private javax.swing.JLabel player2card11;
    private javax.swing.JLabel player2card12;
    private javax.swing.JLabel player2card13;
    private javax.swing.JLabel player2card2;
    private javax.swing.JLabel player2card3;
    private javax.swing.JLabel player2card4;
    private javax.swing.JLabel player2card5;
    private javax.swing.JLabel player2card6;
    private javax.swing.JLabel player2card7;
    private javax.swing.JLabel player2card8;
    private javax.swing.JLabel player2card9;
    private javax.swing.JPanel player3;
    private javax.swing.JLabel player3card1;
    private javax.swing.JLabel player3card10;
    private javax.swing.JLabel player3card11;
    private javax.swing.JLabel player3card12;
    private javax.swing.JLabel player3card13;
    private javax.swing.JLabel player3card2;
    private javax.swing.JLabel player3card3;
    private javax.swing.JLabel player3card4;
    private javax.swing.JLabel player3card5;
    private javax.swing.JLabel player3card6;
    private javax.swing.JLabel player3card7;
    private javax.swing.JLabel player3card8;
    private javax.swing.JLabel player3card9;
    private javax.swing.JPanel player4;
    private javax.swing.JLabel player4card1;
    private javax.swing.JLabel player4card10;
    private javax.swing.JLabel player4card11;
    private javax.swing.JLabel player4card12;
    private javax.swing.JLabel player4card13;
    private javax.swing.JLabel player4card2;
    private javax.swing.JLabel player4card3;
    private javax.swing.JLabel player4card4;
    private javax.swing.JLabel player4card5;
    private javax.swing.JLabel player4card6;
    private javax.swing.JLabel player4card7;
    private javax.swing.JLabel player4card8;
    private javax.swing.JLabel player4card9;
    private javax.swing.JPanel player5;
    // End of variables declaration//GEN-END:variables
}
